version: 2.1
jobs:
  build-apk:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter build apk --split-per-abi --release
  upload-artifacts:
    steps:
      - store_artifacts:
            path: /tmp/artifacts
